# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.studiovpc-notebook-role:
resource "aws_iam_role" "studiovpc-notebook-role" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "sagemaker.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    format("arn:aws:iam::%s:policy/studio-vpc-infra-IAM-SageMakerNotebookInstancePolicy",data.aws_caller_identity.current.account_id)
  ]
  max_session_duration = 3600
  name                 = "studiovpc-notebook-role"
  path                 = "/"
  tags                 = {}
  tags_all             = {}

  inline_policy {}
}
