# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_sagemaker_domain.mydomain:
resource "aws_sagemaker_domain" "mydomain" {
  depends_on = [aws_vpc_endpoint.vpce-sm-api]
  app_network_access_type = "VpcOnly"
  auth_mode               = "IAM"
  domain_name             = "vpc-domain"
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags     = {}
  tags_all = {}
  vpc_id   = aws_vpc.vpc-0068c71bc314adf60.id

  default_user_settings {
    execution_role = aws_iam_role.studiovpc-notebook-role.arn
    security_groups = [
      aws_security_group.sg-0f4c99f84f3c31187.id,
    ]
  }
}
