# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.studiovpc-data:
resource "aws_s3_bucket" "studiovpc-data-bucket" {
  bucket         = format("studiovpc-data-%s",data.aws_caller_identity.current.account_id)
  hosted_zone_id = "Z1BKCTXD74EZPE"
  request_payer  = "BucketOwner"
  tags           = {}
  tags_all       = {}

  server_side_encryption_configuration {
    rule {
      bucket_key_enabled = false

      apply_server_side_encryption_by_default {
        kms_master_key_id = aws_kms_key.k_sagemaker.id
        sse_algorithm     = "aws:kms"
      }
    }
  }

  versioning {
    enabled    = false
    mfa_delete = false
  }
  force_destroy = false
  acl           = "private"
  lifecycle {
    ignore_changes = [acl, force_destroy]
  }
}
