# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_sagemaker_user_profile.user1:
resource "aws_sagemaker_user_profile" "user1" {
  domain_id         = aws_sagemaker_domain.mydomain.id
  tags              = {}
  tags_all          = {}
  user_profile_name = "user1"
}
