# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0cdf0919b0826f4b7:
resource "aws_subnet" "subnet-0cdf0919b0826f4b7" {
  assign_ipv6_address_on_creation = false
  availability_zone               = data.aws_availability_zones.az.names[0]
  cidr_block                      = "10.2.1.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name" = "studiovpc-private-subnet"
  }
  tags_all = {
    "Name" = "studiovpc-private-subnet"
  }
  vpc_id = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
