# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_sagemaker_app.arn_aws_sagemaker_app_mydomain_user1_jupyterserver_default:
resource "aws_sagemaker_app" "arn_aws_sagemaker_app_mydomain_user1_jupyterserver_default" {
  depends_on=[aws_sagemaker_user_profile.user1]
  app_name          = "default"
  app_type          = "JupyterServer"
  domain_id         = aws_sagemaker_domain.mydomain.id
  tags              = {}
  tags_all          = {}
  user_profile_name = "user1"

}
