# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.studiovpc-notebook-role__studio-vpc-infra-IAM-SageMakerNotebookInstancePolicy:
resource "aws_iam_role_policy_attachment" "studiovpc-notebook-role__studio-vpc-infra-IAM-SageMakerNotebookInstancePolicy" {
  policy_arn = aws_iam_policy.studio-vpc-infra-IAM-SageMakerNotebookInstancePolicy.arn
  role       = aws_iam_role.studiovpc-notebook-role.id
}
