# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-0cf252a93b44fe2c2:
resource "aws_route_table" "rtb-0cf252a93b44fe2c2" {
  propagating_vgws = []
  route            = []
  tags             = {}
  tags_all         = {}
  vpc_id           = aws_vpc.vpc-0068c71bc314adf60.id
}
