# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket_policy.studiovpc-data:
resource "aws_s3_bucket_policy" "studiovpc-data-policy" {
  bucket = format("studiovpc-data-%s",data.aws_caller_identity.current.account_id)
  depends_on=[aws_s3_bucket.studiovpc-data-bucket]
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "s3:GetObject",
            "s3:PutObject",
            "s3:ListBucket",
          ]
          Condition = {
            NotIpAddress = {
              "aws:SourceIp" = "81.96.210.11/32"
            }
            StringNotEquals = {
              "aws:sourceVpce" = "vpce-0ca818e2255add312"
            }
          }
          Effect    = "Deny"
          Principal = "*"
          Resource = [
            format("arn:aws:s3:::studiovpc-data-%s/*",data.aws_caller_identity.current.account_id),
            format("arn:aws:s3:::studiovpc-data-%s",data.aws_caller_identity.current.account_id)
          ]
        },
      ]
      Version = "2008-10-17"
    }
  )
}
