# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0e74853ab215fa9d4:
resource "aws_security_group" "sg-0e74853ab215fa9d4" {
  description = "Allow TLS for VPC Endpoint"
  tags = {
    "Name" = "studiovpc-endpoint-security-group"
  }
  tags_all = {
    "Name" = "studiovpc-endpoint-security-group"
  }
  vpc_id = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
