# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-032096a0f5e3b45b6:
resource "aws_vpc_endpoint" "vpce-032096a0f5e3b45b6" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]
  service_name = format("com.amazonaws.%s.ssm",data.aws_region.current.name)
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-052dea3e2177ffc15:
resource "aws_vpc_endpoint" "vpce-052dea3e2177ffc15" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("com.amazonaws.%s.monitoring",data.aws_region.current.name)
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0751e22c54f965289:
resource "aws_vpc_endpoint" "vpce-0751e22c54f965289" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("com.amazonaws.%s.sagemaker.api",data.aws_region.current.name)
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-07a63875d3f60ca7f:
resource "aws_vpc_endpoint" "vpce-07a63875d3f60ca7f" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]
  service_name = format("com.amazonaws.%s.sagemaker.runtime",data.aws_region.current.name)
  
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-08e2a9d0811444081:
resource "aws_vpc_endpoint" "vpce-08e2a9d0811444081" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("com.amazonaws.%s.ecr.api",data.aws_region.current.name)
  
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0c706e86a36544406:
resource "aws_vpc_endpoint" "vpce-0c706e86a36544406" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("aws.sagemaker.%s.notebook",data.aws_region.current.name)

  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0ca818e2255add312:
resource "aws_vpc_endpoint" "vpce-0ca818e2255add312" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "s3:GetObject",
            "s3:PutObject",
            "s3:ListBucket",
          ]
          Effect    = "Allow"
          Principal = "*"
          Resource = [
            format("arn:aws:s3:::studiovpc-data-%s",data.aws_caller_identity.current.account_id),
            format("arn:aws:s3:::studiovpc-models-%s",data.aws_caller_identity.current.account_id),
            format("arn:aws:s3:::studiovpc-data-%s/*",data.aws_caller_identity.current.account_id),
            format("arn:aws:s3:::studiovpc-models-%s/*",data.aws_caller_identity.current.account_id)
          ]
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = false
  route_table_ids = [
    aws_route_table.rtb-0cf252a93b44fe2c2.id,
  ]
  security_group_ids = []
  
  service_name = format("com.amazonaws.%s.s3",data.aws_region.current.name)
  
  subnet_ids         = []
  tags               = {}
  tags_all           = {}
  vpc_endpoint_type  = "Gateway"
  vpc_id             = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0d09a2db3bd075da7:
resource "aws_vpc_endpoint" "vpce-0d09a2db3bd075da7" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("com.amazonaws.%s.ecr.dkr",data.aws_region.current.name)
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0d6a913162d819897:
resource "aws_vpc_endpoint" "vpce-0d6a913162d819897" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]
  service_name = format("com.amazonaws.%s.logs",data.aws_region.current.name)

  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_endpoint.vpce-0e090e33e44dd8ddf:
resource "aws_vpc_endpoint" "vpce-0e090e33e44dd8ddf" {
  policy = jsonencode(
    {
      Statement = [
        {
          Action    = "*"
          Effect    = "Allow"
          Principal = "*"
          Resource  = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  private_dns_enabled = true
  route_table_ids     = []
  security_group_ids = [
    aws_security_group.sg-0e74853ab215fa9d4.id,
  ]

  service_name = format("com.amazonaws.%s.sts",data.aws_region.current.name)
  subnet_ids = [
    aws_subnet.subnet-0cdf0919b0826f4b7.id,
  ]
  tags              = {}
  tags_all          = {}
  vpc_endpoint_type = "Interface"
  vpc_id            = aws_vpc.vpc-0068c71bc314adf60.id

  timeouts {}
}
